### ISSUE TITLE
Special:LinkTitles queries entire page table every page

### ISSUE THREAD

**Issue by labster** [bovender/LinkTitles#17]
Hi.  I'm a security reviewer from the Miraheze wiki farm.  The good news is that I don't see any security concerns in your code.

But as usual in my readthroughs, I see other things.  When you mention that things might take seconds on a wiki farm if your wiki has 500 pages, I get a little worried about performance.

I was thinking about only enabling the special page.  But this isn't any more efficient than a page save, because we request the whole page table every time.  If there's enough pages, this can pretty easily get into the megabytes of DB traffic with a single request, just for the page names.

Can you refactor this code to only fetch page_title data once per request?  Probably save it in a class variable, and then just check to see that we're not linking the current page inside parseContent().

**Comment by bovender** [comment]
Thanks for your thoughts. I'm definitively eager to optimize the algorithm, especially since there have been [complaints](https://www.mediawiki.org/wiki/Extension_talk:LinkTitles#Takes_too_long_to_run) about the extension being too slow.

It did take a couple of seconds to parse this one, extremely long page on our in-house Wiki. However, since then I moved the Wiki from the hosted webspace to my own server (dual core, 6 GB RAM, SSD), and it is considerably faster now. Having said that, I guess that the bottleneck is the regex work, though I'd have to benchmark this.

Now, as for your suggestion to cache the page_title date, I'm not sure I'm on the same page as you yet. When a user saves a page, an HTTP request is made, and the LinkTitles extension is invoked once. If someone else were to save a page at the same time, this would happen in a separate request, and storing the `page_title` data in a static class variable would not be helpful because it can't be shared between requests?

Am I missing something?

**Comment by labster** [comment]
Yes.  You missed the title of the issue `Special:LinkTitles`.  The call stack is LinkTitles::Special::execute -> loop ( LinkTitles::Extension::process_page -> LinkTitles::Extension::parseContent ).  So the extension is invoked many times.

**Comment by bovender** [comment]
@labster Please have a look at #18. The performance on my development machine is negligible, but of course my playground wiki has only 108 pages...

**Comment by bovender** [comment]
Closed by #19.
