### ISSUE TITLE
Articles with non (Main) namespace

### ISSUE THREAD

**Issue by benvarkey** [bovender/LinkTitles#27]
`Main Page` is picked up correctly, but `Namespace:Article` or `Article` are not picked up.
I read that there is support for namespace, but, how do I get it?

**Comment by bovender** [comment]
Hi,

sorry for the delay in replying.

Once you have defined a custom namespace in your `LocalSettings.php` as described in the [MediaWiki documentation](https://www.mediawiki.org/wiki/Manual:Using_custom_namespaces#Creating_a_custom_namespace):

    define( 'NS_MYNAMESPACE', 3000);
    $wgExtraNamespaces[NS_MYNAMESPACE] = 'My_namespace';

you can enable linking in this namespace by adding a value to the `$wgLinkTitlesNamespaces` array:

    $wgLinkTitlesNamespaces[] = NS_MYNAMESPACE;

However, I believe there is a bug. Pages from namespaces other than the default namespace are not prefixed with the namespace. As a result, they are 'red' links, at least on my development system. @c0nnex, do you have thoughts on this?

**Comment by bovender** [comment]
@benvarkey The upcoming version 5 (which I expect to release in the next couple of days) will address this issue. However, I have decided to not automatically link something like `custom_namespace:Article`, because I think if someone goes out of their way to type a namespace-qualified page title, they might just as well add the linking brackets too.
