### ISSUE TITLE
Knowing which pages have been linked

### ISSUE THREAD

**Issue by wanjaus** [bovender/LinkTitles#61]
Product | Version
MediaWiki | 1.37.1
PHP | 7.4.28 (fpm-fcgi)
MariaDB | 10.3.28-MariaDB
LinkTitles|8.0.1

This is a great extension that I am running on a quite a huge wiki with about 20,000 entries. When running it in CMD, I can see the number of pages counter increasing but I would like to know which page that is for purposes of some quality control. Is there a known way to check this?

**Comment by bovender** [comment]
Currently there is no way to have the script output the page title (cf. #48).

However it occurred to me to introduce a 'verbose' option which would cause the progress and page titles to be printed line by line.

I'm hesitant to have it overwrite the current line in the terminal because it might look ugly when a page title is shorter than the previous one, and it is not trivial to erase entire screen lines with PHP. So maybe producing one line per page processed in the 'verbose' mode might do?
